### ISSUE TITLE
Received structured exception #0xc0000005

### ISSUE THREAD

**Issue by schilling3003** [pinokiofactory/bolt#1]
I keep getting this error when trying to run:

Microsoft Windows [Version 10.0.22631.4317]
(c) Microsoft Corporation. All rights reserved.

F:\pinokio\api\bolt.git\app>conda_hook && conda deactivate && conda deactivate && conda deactivate && conda activate base && npm run dev

> dev
> remix vite:dev
*** Received structured exception #0xc0000005: access violation; stack: 7ff81614307f 7ff6b9c3bbdb 7ff6b9c3bca3 7ff6b9bdda3c 7ff6b9bdd9e7 7ff6b947372e 7ff6b9473a3f 7ff6b8261ed6 7ff6b959d67f 7ff6b95a4916 7ff6b959db83 7ff6b95a4916 7ff6b959b51c 7ff6b8251e61 7ff6bad4cb6f 7ff82bf6257c 7ff82cf2af07
MiniflareCoreError [ERR_RUNTIME_FAILURE]: The Workers runtime failed to start. There is likely additional logging output above.
    at Miniflare2.#assembleAndUpdateConfig (F:\pinokio\api\bolt.git\app\node_modules\miniflare\src\index.ts:1404:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Mutex.runWith (F:\pinokio\api\bolt.git\app\node_modules\miniflare\src\workers\shared\sync.ts:66:45)
    at async Miniflare2.#waitForReady (F:\pinokio\api\bolt.git\app\node_modules\miniflare\src\index.ts:1486:3)
    at async Miniflare2._getProxyClient (F:\pinokio\api\bolt.git\app\node_modules\miniflare\src\index.ts:1692:3)
    at async Miniflare2.getBindings (F:\pinokio\api\bolt.git\app\node_modules\miniflare\src\index.ts:1715:23)
    at async getPlatformProxy (F:\pinokio\api\bolt.git\app\node_modules\wrangler\src\api\integrations\platform\index.ts:126:24)
    at async configureServer (F:\pinokio\api\bolt.git\app\node_modules\@remix-run\dev\dist\vite\cloudflare-proxy-plugin.js:55:11)
    at async _createServer (file:///F:/pinokio/api/bolt.git/app/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:63080:20)
    at async configResolved (F:\pinokio\api\bolt.git\app\node_modules\@remix-run\dev\dist\vite\plugin.js:748:27)
    at async Promise.all (index 3)
    at async resolveConfig (file:///F:/pinokio/api/bolt.git/app/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:66404:3)
    at async _createServer (file:///F:/pinokio/api/bolt.git/app/node_modules/vite/dist/node/chunks/dep-BWSbWtLw.js:62758:18)
    at async dev (F:\pinokio\api\bolt.git\app\node_modules\@remix-run\dev\dist\vite\dev.js:39:16)
    at async Object.viteDev (F:\pinokio\api\bolt.git\app\node_modules\@remix-run\dev\dist\cli\commands.js:220:3)
    at async Object.run (F:\pinokio\api\bolt.git\app\node_modules\@remix-run\dev\dist\cli\run.js:271:7) {
  code: 'ERR_RUNTIME_FAILURE',
  cause: undefined
}

(base) F:\pinokio\api\bolt.git\app>

**Comment by hello-adam-martin** [comment]
Same issue for me. Tried re installing... same error.
